### ISSUE TITLE
Your GH_TOKEN is showing

### ISSUE THREAD

**Issue by jhuckaby** [getswell/getswell#189]
Your `package.json` file has a token showing:

```js
    "gh-publish": "export GH_TOKEN=b9e252e0b0404c2d8fbe403ca2a42dbd6dd13334 && electron-builder build --x64 --mac -p always"
```

Apologies if this was intentional, it just looked like it might be something private, and not meant to be visible to the public.

**Comment by texpatnyc** [comment]
Thank you!
